@startuml
title Контекстная диаграмма для системы «Тёплый дом»

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Context.puml

Person(user, "Пользователь", "Пользователь системы управления умным домом")
System(system, "Система управления умным домом", "Система для управления отоплением и умными устройствами")

System_Ext(internet, "Интернет", "Сеть для подключения устройств")
System_Ext(heatingDevice, "Устройство отопления", "Управляет отоплением в доме")
System_Ext(lightDevice, "Устройство освещения", "Управляет освещением в доме")
System_Ext(gateDevice, "Автоматические ворота", "Управляет автоматическими воротами")

Rel(user, system, "Использует")
Rel(system, internet, "Подключается к")
Rel(system, heatingDevice, "Управляет")
Rel(system, lightDevice, "Управляет")
Rel(system, gateDevice, "Управляет")

@enduml∆