@startuml
title Контекстная диаграмма микросервисной архитектуры для системы «Тёплый дом»

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Context.puml


actor User as user
actor MobileApp as mobileApp
actor WebApp as webApp

rectangle "Система «Тёплый дом»" {
    rectangle "Home Service" as homeService {
        [Light Service]
        [Temperature Service]
        [Gate Service]
    }
}

user --> homeService : Управление домом
mobileApp --> homeService : API запросы
webApp --> homeService : API запросы

homeService --> [Light Service] : Запросы на управление освещением
homeService --> [Temperature Service] : Запросы на управление температурой
homeService --> [Gate Service] : Запросы на управление воротами

@enduml